services:
  #  api:
  #    image: api
  #    build:
  #      context: .
  #      dockerfile: API/Dockerfile
  postgres:
    container_name: postgres2
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: social_network
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5435:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
  minio:
    container_name: minio2
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    restart: always
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
volumes:
  postgres-data:
  minio_data: